package com.mandeep;

import java.net.ServerSocket;
import java.net.DatagramSocket;
import java.lang.Math;
import java.io.IOException;

//This class will generate a number between [10000,40000) and check if it is valid and available port number.

public class PortGenerator{
	
	//This function will generate and return a random port number and check if it's available or not. 
	
    int getPort(){
        int randomPort = 0;
        
        do {
        	
            randomPort = (int)(Math.random()*30000 + 10000); 
        
        } while(!available(randomPort));
        return randomPort;
    }

    //this function will check if the port number generated by getPort function is available or not.
    
    boolean available(int port) { 
        ServerSocket ss = null;
        DatagramSocket ds = null;
        try {
            ss = new ServerSocket(port); 
            ss.setReuseAddress(true);
            ds = new DatagramSocket(port);
            ds.setReuseAddress(true);
            return true;
        } catch (IOException e) {

        } finally {
            if (ds != null) {
                ds.close();
            }

            if (ss != null) {
                try {
                    ss.close();
                } catch (IOException e) {
                }
            }
        }

        return false;
    }
}